// Package httptransport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httptransport

// Defines values for GetV1MediaVideosParamsTab.
const (
	Bookmarked GetV1MediaVideosParamsTab = "bookmarked"
	Favorite   GetV1MediaVideosParamsTab = "favorite"
	Uploaded   GetV1MediaVideosParamsTab = "uploaded"
	Viewed     GetV1MediaVideosParamsTab = "viewed"
)

// Valid indicates whether the value is a known member of the GetV1MediaVideosParamsTab enum.
func (e GetV1MediaVideosParamsTab) Valid() bool {
	switch e {
	case Bookmarked:
		return true
	case Favorite:
		return true
	case Uploaded:
		return true
	case Viewed:
		return true
	default:
		return false
	}
}

// AlbumRequest defines model for AlbumRequest.
type AlbumRequest struct {
	Title string `json:"title"`
}

// MediaResponse defines model for MediaResponse.
type MediaResponse struct {
	Checksum         string  `json:"checksum"`
	ContentType      *string `json:"content_type,omitempty"`
	CreatedAt        string  `json:"created_at"`
	ID               string  `json:"id"`
	MediaType        string  `json:"media_type"`
	OriginalFilename string  `json:"original_filename"`
	Size             int64   `json:"size"`
	UploadedBy       string  `json:"uploaded_by"`
}

// MediaUploadRequest defines model for MediaUploadRequest.
type MediaUploadRequest struct {
	File string `json:"file"`
}

// MusicListResponse defines model for MusicListResponse.
type MusicListResponse struct {
	Tracks []MusicResponse `json:"tracks"`
}

// MusicResponse defines model for MusicResponse.
type MusicResponse struct {
	Artist    string   `json:"artist"`
	CreatedAt string   `json:"created_at"`
	Duration  *float64 `json:"duration,omitempty"`
	ID        string   `json:"id"`
	IsSaved   bool     `json:"is_saved"`
	MediaID   string   `json:"media_id"`
	Title     string   `json:"title"`
	UserID    string   `json:"user_id"`
}

// MusicUploadRequest defines model for MusicUploadRequest.
type MusicUploadRequest struct {
	Artist *string `json:"artist,omitempty"`
	File   string  `json:"file"`
	Title  *string `json:"title,omitempty"`
}

// RecordViewRequest defines model for RecordViewRequest.
type RecordViewRequest struct {
	Seconds *float64 `json:"seconds,omitempty"`
}

// RenditionResponse defines model for RenditionResponse.
type RenditionResponse struct {
	ContentType string  `json:"content_type"`
	CreatedAt   string  `json:"created_at"`
	Duration    float64 `json:"duration"`
	Height      int     `json:"height"`
	ID          string  `json:"id"`
	Size        int64   `json:"size"`
}

// VideoAlbumListItem defines model for VideoAlbumListItem.
type VideoAlbumListItem struct {
	ID     *string         `json:"id,omitempty"`
	Title  string          `json:"title"`
	Videos []VideoResponse `json:"videos"`
}

// VideoAlbumListResponse defines model for VideoAlbumListResponse.
type VideoAlbumListResponse struct {
	Albums []VideoAlbumListItem `json:"albums"`
}

// VideoAlbumResponse defines model for VideoAlbumResponse.
type VideoAlbumResponse struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

// VideoFlagResponse defines model for VideoFlagResponse.
type VideoFlagResponse struct {
	Bookmarked *bool `json:"bookmarked,omitempty"`
	Favorited  *bool `json:"favorited,omitempty"`
}

// VideoLikeResponse defines model for VideoLikeResponse.
type VideoLikeResponse struct {
	Liked      bool `json:"liked"`
	LikesCount int  `json:"likes_count"`
}

// VideoResponse defines model for VideoResponse.
type VideoResponse struct {
	AlbumID            *string             `json:"album_id,omitempty"`
	CreatedAt          string              `json:"created_at"`
	Duration           *float64            `json:"duration,omitempty"`
	ID                 string              `json:"id"`
	BookmarkedByViewer bool                `json:"is_bookmarked_by_current"`
	FavoritedByViewer  bool                `json:"is_favorited_by_current"`
	LikedByViewer      bool                `json:"is_liked_by_current"`
	LikesCount         int                 `json:"likes_count"`
	MediaID            string              `json:"media_id"`
	OriginalFilename   *string             `json:"original_filename,omitempty"`
	OwnerID            *string             `json:"owner_id,omitempty"`
	Renditions         []RenditionResponse `json:"renditions"`
	Status             string              `json:"status"`
	Title              string              `json:"title"`
	UpdatedAt          string              `json:"updated_at"`
	ViewsCount         int                 `json:"views_count"`
}

// VideoUploadRequest defines model for VideoUploadRequest.
type VideoUploadRequest struct {
	AlbumId *string `json:"album_id,omitempty"`
	File    string  `json:"file"`
	Heights *string `json:"heights,omitempty"`
	Title   *string `json:"title,omitempty"`
}

// VideoViewResponse defines model for VideoViewResponse.
type VideoViewResponse struct {
	ViewsCount int `json:"views_count"`
}

// AlbumID defines model for AlbumID.
type AlbumID = string

// MediaID defines model for MediaID.
type MediaID = string

// TrackID defines model for TrackID.
type TrackID = string

// VideoID defines model for VideoID.
type VideoID = string

// AlbumOK defines model for AlbumOK.
type AlbumOK = VideoAlbumResponse

// MediaOK defines model for MediaOK.
type MediaOK = MediaResponse

// MusicListOK defines model for MusicListOK.
type MusicListOK = MusicListResponse

// MusicOK defines model for MusicOK.
type MusicOK = MusicResponse

// VideoAlbumsOK defines model for VideoAlbumsOK.
type VideoAlbumsOK = VideoAlbumListResponse

// VideoFlagOK defines model for VideoFlagOK.
type VideoFlagOK = VideoFlagResponse

// VideoLikeOK defines model for VideoLikeOK.
type VideoLikeOK = VideoLikeResponse

// VideoOK defines model for VideoOK.
type VideoOK = VideoResponse

// VideoViewOK defines model for VideoViewOK.
type VideoViewOK = VideoViewResponse

// GetV1MediaMusicParams defines parameters for GetV1MediaMusic.
type GetV1MediaMusicParams struct {
	OwnerId *string `form:"owner_id,omitempty" json:"owner_id,omitempty"`
}

// GetV1MediaVideosParams defines parameters for GetV1MediaVideos.
type GetV1MediaVideosParams struct {
	OwnerId *string                    `form:"owner_id,omitempty" json:"owner_id,omitempty"`
	Tab     *GetV1MediaVideosParamsTab `form:"tab,omitempty" json:"tab,omitempty"`
	Q       *string                    `form:"q,omitempty" json:"q,omitempty"`
}

// GetV1MediaVideosParamsTab defines parameters for GetV1MediaVideos.
type GetV1MediaVideosParamsTab string

// PostV1MediaMultipartRequestBody defines body for PostV1Media for multipart/form-data ContentType.
type PostV1MediaMultipartRequestBody = MediaUploadRequest

// PostV1MediaMusicMultipartRequestBody defines body for PostV1MediaMusic for multipart/form-data ContentType.
type PostV1MediaMusicMultipartRequestBody = MusicUploadRequest

// PostV1MediaVideosMultipartRequestBody defines body for PostV1MediaVideos for multipart/form-data ContentType.
type PostV1MediaVideosMultipartRequestBody = VideoUploadRequest

// PostV1MediaVideosAlbumsFormdataRequestBody defines body for PostV1MediaVideosAlbums for application/x-www-form-urlencoded ContentType.
type PostV1MediaVideosAlbumsFormdataRequestBody = AlbumRequest

// PostV1MediaVideosVideoIDViewJSONRequestBody defines body for PostV1MediaVideosVideoIDView for application/json ContentType.
type PostV1MediaVideosVideoIDViewJSONRequestBody = RecordViewRequest
