// Package httptransport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httptransport

// ConversationResponse defines model for ConversationResponse.
type ConversationResponse struct {
	Archived       bool             `json:"archived"`
	CreatedAt      string           `json:"created_at"`
	ID             string           `json:"id"`
	LastMessage    *MessageResponse `json:"last_message,omitempty"`
	Muted          bool             `json:"muted"`
	ParticipantIDs []string         `json:"participant_ids"`
	Pinned         bool             `json:"pinned"`
	UpdatedAt      string           `json:"updated_at"`
}

// ConversationsResponse defines model for ConversationsResponse.
type ConversationsResponse struct {
	Conversations []ConversationResponse `json:"conversations"`
}

// DirectConversationRequest defines model for DirectConversationRequest.
type DirectConversationRequest struct {
	OtherUserID string `json:"other_user_id"`
}

// MessageRequest defines model for MessageRequest.
type MessageRequest struct {
	Body    string  `json:"body"`
	MediaID *string `json:"media_id,omitempty"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Body           string  `json:"body"`
	ConversationID string  `json:"conversation_id"`
	CreatedAt      string  `json:"created_at"`
	Deleted        bool    `json:"deleted"`
	EditedAt       *string `json:"edited_at,omitempty"`
	ID             string  `json:"id"`
	MediaID        *string `json:"media_id,omitempty"`
	SenderID       string  `json:"sender_id"`
}

// MessagesResponse defines model for MessagesResponse.
type MessagesResponse struct {
	HasMore  bool              `json:"has_more"`
	Messages []MessageResponse `json:"messages"`
}

// PresenceListResponse defines model for PresenceListResponse.
type PresenceListResponse struct {
	Presence []PresenceResponse `json:"presence"`
}

// PresenceResponse defines model for PresenceResponse.
type PresenceResponse struct {
	Online bool   `json:"online"`
	UserID string `json:"user_id"`
}

// ConversationID defines model for ConversationID.
type ConversationID = string

// MessageID defines model for MessageID.
type MessageID = string

// UserID defines model for UserID.
type UserID = string

// ConversationOK defines model for ConversationOK.
type ConversationOK = ConversationResponse

// ConversationsOK defines model for ConversationsOK.
type ConversationsOK = ConversationsResponse

// MessageOK defines model for MessageOK.
type MessageOK = MessageResponse

// MessagesOK defines model for MessagesOK.
type MessagesOK = MessagesResponse

// PresenceListOK defines model for PresenceListOK.
type PresenceListOK = PresenceListResponse

// PresenceOK defines model for PresenceOK.
type PresenceOK = PresenceResponse

// GetV1MessagingConversationsParams defines parameters for GetV1MessagingConversations.
type GetV1MessagingConversationsParams struct {
	Archived *bool `form:"archived,omitempty" json:"archived,omitempty"`
}

// GetV1MessagingConversationsConversationIDMessagesParams defines parameters for GetV1MessagingConversationsConversationIDMessages.
type GetV1MessagingConversationsConversationIDMessagesParams struct {
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetV1MessagingPresenceParams defines parameters for GetV1MessagingPresence.
type GetV1MessagingPresenceParams struct {
	UserIds string `form:"user_ids" json:"user_ids"`
}

// GetV1NotificationsStreamParams defines parameters for GetV1NotificationsStream.
type GetV1NotificationsStreamParams struct {
	AccessToken *string `form:"access_token,omitempty" json:"access_token,omitempty"`
}

// PostV1MessagingConversationsDirectJSONRequestBody defines body for PostV1MessagingConversationsDirect for application/json ContentType.
type PostV1MessagingConversationsDirectJSONRequestBody = DirectConversationRequest

// PostV1MessagingConversationsConversationIDMessagesJSONRequestBody defines body for PostV1MessagingConversationsConversationIDMessages for application/json ContentType.
type PostV1MessagingConversationsConversationIDMessagesJSONRequestBody = MessageRequest

// PatchV1MessagingMessagesMessageIDJSONRequestBody defines body for PatchV1MessagingMessagesMessageID for application/json ContentType.
type PatchV1MessagingMessagesMessageIDJSONRequestBody = MessageRequest
