// Package httptransport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httptransport

import (
	"time"
)

// Defines values for StatusResponseStatus.
const (
	DatabaseUnavailable StatusResponseStatus = "database_unavailable"
	Ok                  StatusResponseStatus = "ok"
	Ready               StatusResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the StatusResponseStatus enum.
func (e StatusResponseStatus) Valid() bool {
	switch e {
	case DatabaseUnavailable:
		return true
	case Ok:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for UserResponseStatus.
const (
	Active  UserResponseStatus = "active"
	Blocked UserResponseStatus = "blocked"
	Pending UserResponseStatus = "pending"
)

// Valid indicates whether the value is a known member of the UserResponseStatus enum.
func (e UserResponseStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Blocked:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken      string `json:"access_token"`
	ExpiresIn        int64  `json:"expires_in"`
	RefreshExpiresIn int64  `json:"refresh_expires_in"`
	RefreshToken     string `json:"refresh_token"`

	// TokenType Example: Bearer
	TokenType string       `json:"token_type"`
	User      UserResponse `json:"user"`
}

// EmailRequest defines model for EmailRequest.
type EmailRequest struct {
	Email string `json:"email"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// PermissionsResponse defines model for PermissionsResponse.
type PermissionsResponse struct {
	Permissions []string `json:"permissions"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	NewPassword string `json:"new_password"`
	Token       string `json:"token"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status StatusResponseStatus `json:"status"`
}

// StatusResponseStatus defines model for StatusResponse.Status.
type StatusResponseStatus string

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Token string `json:"token"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt  time.Time          `json:"created_at"`
	Email      string             `json:"email"`
	Id         string             `json:"id"`
	LastSeenAt *time.Time         `json:"last_seen_at,omitempty"`
	Status     UserResponseStatus `json:"status"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

// UserResponseStatus defines model for UserResponse.Status.
type UserResponseStatus string

// IdentityConflict defines model for IdentityConflict.
type IdentityConflict = ErrorResponse

// InvalidCredentials defines model for InvalidCredentials.
type InvalidCredentials = ErrorResponse

// InvalidJSON defines model for InvalidJSON.
type InvalidJSON = ErrorResponse

// InvalidRefreshToken defines model for InvalidRefreshToken.
type InvalidRefreshToken = ErrorResponse

// InvalidVerificationToken defines model for InvalidVerificationToken.
type InvalidVerificationToken = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ErrorResponse

// ConfirmRegistrationJSONRequestBody defines body for ConfirmRegistration for application/json ContentType.
type ConfirmRegistrationJSONRequestBody = TokenRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = EmailRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// RequestRegistrationConfirmationJSONRequestBody defines body for RequestRegistrationConfirmation for application/json ContentType.
type RequestRegistrationConfirmationJSONRequestBody = EmailRequest
