COMMENT_CREATED_EVENT = "comment.created"
PASSWORD_RESET_REQUESTED_EVENT = "email.password_reset_requested"
POST_CREATED_EVENT = "post.created"
POST_LIKE_TOGGLED_EVENT = "post.like_toggled"
PROFILE_PHOTO_DELETED_EVENT = "profile_photo.deleted"
REGISTRATION_CONFIRMATION_REQUESTED_EVENT = "email.registration_confirmation_requested"
USER_REGISTERED_EVENT = "user.registered"
FRIEND_REQUESTED_EVENT = "friend.requested"
FRIEND_ACCEPTED_EVENT = "friend.accepted"
FRIEND_REMOVED_EVENT = "friend.removed"
FRIEND_REQUEST_CANCELLED_EVENT = "friend.request_cancelled"
MESSAGE_SENT_EVENT = "message.sent"
MESSAGE_EDITED_EVENT = "message.edited"
MESSAGE_DELETED_EVENT = "message.deleted"
MESSAGE_MEDIA_REMOVED_EVENT = "message.media_removed"
MESSAGE_READ_EVENT = "message.read"

ANALYTICS_EVENT_TYPES = (
    USER_REGISTERED_EVENT,
    POST_CREATED_EVENT,
    POST_LIKE_TOGGLED_EVENT,
    COMMENT_CREATED_EVENT,
    PROFILE_PHOTO_DELETED_EVENT,
    FRIEND_REQUESTED_EVENT,
    FRIEND_ACCEPTED_EVENT,
    FRIEND_REMOVED_EVENT,
    FRIEND_REQUEST_CANCELLED_EVENT,
    MESSAGE_SENT_EVENT,
    MESSAGE_EDITED_EVENT,
    MESSAGE_DELETED_EVENT,
    MESSAGE_MEDIA_REMOVED_EVENT,
    MESSAGE_READ_EVENT,
)
