// Package httptransport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httptransport

// CommentResponse defines model for CommentResponse.
type CommentResponse struct {
	AuthorID  string `json:"author_id"`
	Body      string `json:"body"`
	CreatedAt string `json:"created_at"`
	ID        string `json:"id"`
	PostID    string `json:"post_id"`
	UpdatedAt string `json:"updated_at"`
}

// CommentsResponse defines model for CommentsResponse.
type CommentsResponse struct {
	Comments []CommentResponse `json:"comments"`
}

// LikeResponse defines model for LikeResponse.
type LikeResponse struct {
	Liked  bool   `json:"liked"`
	PostID string `json:"post_id"`
	UserID string `json:"user_id"`
}

// PostRequest defines model for PostRequest.
type PostRequest struct {
	Body     string    `json:"body"`
	MediaIDs *[]string `json:"media_ids,omitempty"`
}

// PostResponse defines model for PostResponse.
type PostResponse struct {
	AuthorID      string   `json:"author_id"`
	Body          string   `json:"body"`
	CommentsCount int      `json:"comments_count"`
	CreatedAt     string   `json:"created_at"`
	ID            string   `json:"id"`
	LikedByViewer bool     `json:"is_liked_by_current"`
	LikedUserIDs  []string `json:"liked_user_ids"`
	LikesCount    int      `json:"likes_count"`
	MediaIDs      []string `json:"media_ids"`
	UpdatedAt     string   `json:"updated_at"`
}

// PostsResponse defines model for PostsResponse.
type PostsResponse struct {
	Posts []PostResponse `json:"posts"`
}

// CommentID defines model for CommentID.
type CommentID = string

// PostID defines model for PostID.
type PostID = string

// CommentCreated defines model for CommentCreated.
type CommentCreated = CommentResponse

// CommentsOK defines model for CommentsOK.
type CommentsOK = CommentsResponse

// LikeOK defines model for LikeOK.
type LikeOK = LikeResponse

// PostCreated defines model for PostCreated.
type PostCreated = PostResponse

// PostOK defines model for PostOK.
type PostOK = PostResponse

// PostsOK defines model for PostsOK.
type PostsOK = PostsResponse

// GetV1ContentFeedParams defines parameters for GetV1ContentFeed.
type GetV1ContentFeedParams struct {
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetV1ContentPostsPostIDCommentsParams defines parameters for GetV1ContentPostsPostIDComments.
type GetV1ContentPostsPostIDCommentsParams struct {
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostV1ContentPostsJSONRequestBody defines body for PostV1ContentPosts for application/json ContentType.
type PostV1ContentPostsJSONRequestBody = PostRequest

// PatchV1ContentPostsPostIDJSONRequestBody defines body for PatchV1ContentPostsPostID for application/json ContentType.
type PatchV1ContentPostsPostIDJSONRequestBody = PostRequest

// PostV1ContentPostsPostIDCommentsJSONRequestBody defines body for PostV1ContentPostsPostIDComments for application/json ContentType.
type PostV1ContentPostsPostIDCommentsJSONRequestBody = PostRequest
