// Package httptransport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httptransport

import (
	"time"
)

// Defines values for StatusResponseStatus.
const (
	StatusResponseStatusDatabaseUnavailable StatusResponseStatus = "database_unavailable"
	StatusResponseStatusOk                  StatusResponseStatus = "ok"
	StatusResponseStatusReady               StatusResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the StatusResponseStatus enum.
func (e StatusResponseStatus) Valid() bool {
	switch e {
	case StatusResponseStatusDatabaseUnavailable:
		return true
	case StatusResponseStatusOk:
		return true
	case StatusResponseStatusReady:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status StatusResponseStatus `json:"status"`
}

// StatusResponseStatus defines model for StatusResponse.Status.
type StatusResponseStatus string

// VideoStatsResponse defines model for VideoStatsResponse.
type VideoStatsResponse struct {
	AverageWatchSeconds float64    `json:"average_watch_seconds"`
	CompletedViews      int64      `json:"completed_views"`
	LastViewedAt        *time.Time `json:"last_viewed_at,omitempty"`
	TotalWatchSeconds   float64    `json:"total_watch_seconds"`
	UniqueViewers       int64      `json:"unique_viewers"`
	VideoId             string     `json:"video_id"`
	Views               int64      `json:"views"`
}

// ViewerVideoStatsListResponse defines model for ViewerVideoStatsListResponse.
type ViewerVideoStatsListResponse struct {
	Videos []ViewerVideoStatsResponse `json:"videos"`
}

// ViewerVideoStatsResponse defines model for ViewerVideoStatsResponse.
type ViewerVideoStatsResponse struct {
	AverageWatchSeconds float64   `json:"average_watch_seconds"`
	LastViewedAt        time.Time `json:"last_viewed_at"`
	VideoId             string    `json:"video_id"`
	Views               int64     `json:"views"`
	WatchSeconds        float64   `json:"watch_seconds"`
}

// VideoID defines model for VideoID.
type VideoID = string

// AnalyticsUnavailable defines model for AnalyticsUnavailable.
type AnalyticsUnavailable = ErrorResponse

// DatabaseUnavailable defines model for DatabaseUnavailable.
type DatabaseUnavailable = StatusResponse

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = ErrorResponse

// StatusOK defines model for StatusOK.
type StatusOK = StatusResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListMyVideoStatsParams defines parameters for ListMyVideoStats.
type ListMyVideoStatsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}
