// Package httptransport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httptransport

import (
	"time"
)

// Defines values for GetV1SocialFriendRequestsParamsDirection.
const (
	All      GetV1SocialFriendRequestsParamsDirection = "all"
	Incoming GetV1SocialFriendRequestsParamsDirection = "incoming"
	Outgoing GetV1SocialFriendRequestsParamsDirection = "outgoing"
)

// Valid indicates whether the value is a known member of the GetV1SocialFriendRequestsParamsDirection enum.
func (e GetV1SocialFriendRequestsParamsDirection) Valid() bool {
	switch e {
	case All:
		return true
	case Incoming:
		return true
	case Outgoing:
		return true
	default:
		return false
	}
}

// ActionResponse defines model for ActionResponse.
type ActionResponse struct {
	State string `json:"state"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FriendRequestActionResponse defines model for FriendRequestActionResponse.
type FriendRequestActionResponse struct {
	RequestID *string `json:"request_id,omitempty"`
	State     string  `json:"state"`
}

// FriendRequestResponse defines model for FriendRequestResponse.
type FriendRequestResponse struct {
	CreatedAt   time.Time  `json:"created_at"`
	ID          string     `json:"id"`
	RecipientID string     `json:"recipient_id"`
	RespondedAt *time.Time `json:"responded_at,omitempty"`
	SenderID    string     `json:"sender_id"`
	Status      string     `json:"status"`
}

// FriendRequestsResponse defines model for FriendRequestsResponse.
type FriendRequestsResponse struct {
	Incoming []FriendRequestResponse `json:"incoming"`
	Outgoing []FriendRequestResponse `json:"outgoing"`
}

// PublicFriendsResponse defines model for PublicFriendsResponse.
type PublicFriendsResponse struct {
	Friends []string `json:"friends"`
	Visible bool     `json:"visible"`
}

// RecommendationResponse defines model for RecommendationResponse.
type RecommendationResponse struct {
	CommonFriends int    `json:"common_friends"`
	UserID        string `json:"user_id"`
}

// RecommendationsResponse defines model for RecommendationsResponse.
type RecommendationsResponse struct {
	Recommendations []RecommendationResponse `json:"recommendations"`
}

// RelationshipAccessResponse defines model for RelationshipAccessResponse.
type RelationshipAccessResponse struct {
	IsBlocked        bool `json:"is_blocked"`
	IsFriend         bool `json:"is_friend"`
	IsFriendOfFriend bool `json:"is_friend_of_friend"`
}

// RelationshipsResponse defines model for RelationshipsResponse.
type RelationshipsResponse struct {
	Friends       []string `json:"friends"`
	Subscribers   []string `json:"subscribers"`
	Subscriptions []string `json:"subscriptions"`
}

// RequestID defines model for RequestID.
type RequestID = string

// TargetID defines model for TargetID.
type TargetID = string

// ActionOK defines model for ActionOK.
type ActionOK = ActionResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// FriendRequestActionOK defines model for FriendRequestActionOK.
type FriendRequestActionOK = FriendRequestActionResponse

// FriendRequestsOK defines model for FriendRequestsOK.
type FriendRequestsOK = FriendRequestsResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// PublicFriendsOK defines model for PublicFriendsOK.
type PublicFriendsOK = PublicFriendsResponse

// RecommendationsOK defines model for RecommendationsOK.
type RecommendationsOK = RecommendationsResponse

// RelationshipAccessOK defines model for RelationshipAccessOK.
type RelationshipAccessOK = RelationshipAccessResponse

// RelationshipsOK defines model for RelationshipsOK.
type RelationshipsOK = RelationshipsResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ErrorResponse

// GetV1SocialFriendRequestsParams defines parameters for GetV1SocialFriendRequests.
type GetV1SocialFriendRequestsParams struct {
	Direction *GetV1SocialFriendRequestsParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`
}

// GetV1SocialFriendRequestsParamsDirection defines parameters for GetV1SocialFriendRequests.
type GetV1SocialFriendRequestsParamsDirection string

// GetV1SocialRecommendationsParams defines parameters for GetV1SocialRecommendations.
type GetV1SocialRecommendationsParams struct {
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}
