// Package httptransport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httptransport

// Defines values for StatusResponseStatus.
const (
	DatabaseUnavailable StatusResponseStatus = "database_unavailable"
	Ok                  StatusResponseStatus = "ok"
	Ready               StatusResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the StatusResponseStatus enum.
func (e StatusResponseStatus) Valid() bool {
	switch e {
	case DatabaseUnavailable:
		return true
	case Ok:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// AddPhotoRequest defines model for AddPhotoRequest.
type AddPhotoRequest struct {
	Caption string `json:"caption"`
	MediaID string `json:"media_id"`
}

// AvatarHistoryResponse defines model for AvatarHistoryResponse.
type AvatarHistoryResponse struct {
	Avatars       []AvatarPayload `json:"avatars"`
	CurrentAvatar string          `json:"current_avatar"`
}

// AvatarPayload defines model for AvatarPayload.
type AvatarPayload struct {
	URL       string `json:"avatar_url"`
	CreatedAt string `json:"created_at"`
	ID        string `json:"id"`
	IsCurrent bool   `json:"is_current"`
	MediaID   string `json:"media_id"`
}

// AvatarRequest defines model for AvatarRequest.
type AvatarRequest struct {
	MediaID string `json:"media_id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// PhotoAlbumPayload defines model for PhotoAlbumPayload.
type PhotoAlbumPayload struct {
	CommentPolicy string         `json:"comment_policy"`
	CreatedAt     string         `json:"created_at"`
	Description   string         `json:"description"`
	ID            *string        `json:"id,omitempty"`
	Kind          string         `json:"kind"`
	Photos        []PhotoPayload `json:"photos"`
	Title         string         `json:"title"`
	Visibility    string         `json:"visibility"`
}

// PhotoAlbumRequest defines model for PhotoAlbumRequest.
type PhotoAlbumRequest struct {
	CommentPolicy string `json:"comment_policy"`
	Description   string `json:"description"`
	Title         string `json:"title"`
	Visibility    string `json:"visibility"`
}

// PhotoAlbumResponse defines model for PhotoAlbumResponse.
type PhotoAlbumResponse struct {
	Album PhotoAlbumPayload `json:"album"`
}

// PhotoCommentPayload defines model for PhotoCommentPayload.
type PhotoCommentPayload struct {
	AuthorName string `json:"author_name"`
	Body       string `json:"body"`
	CreatedAt  string `json:"created_at"`
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
}

// PhotoCommentRequest defines model for PhotoCommentRequest.
type PhotoCommentRequest struct {
	Body string `json:"body"`
}

// PhotoCommentsResponse defines model for PhotoCommentsResponse.
type PhotoCommentsResponse struct {
	Comments []PhotoCommentPayload `json:"comments"`
}

// PhotoMediaVisibilityResponse defines model for PhotoMediaVisibilityResponse.
type PhotoMediaVisibilityResponse struct {
	Allowed bool `json:"allowed"`
}

// PhotoPayload defines model for PhotoPayload.
type PhotoPayload struct {
	AlbumID   *string  `json:"album_id,omitempty"`
	Archived  bool     `json:"archived"`
	Caption   *string  `json:"caption,omitempty"`
	CreatedAt string   `json:"created_at"`
	ID        string   `json:"id"`
	Latitude  *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
	MediaID   string   `json:"media_id"`
	URL       string   `json:"photo_url"`
}

// PrivacyRequest defines model for PrivacyRequest.
type PrivacyRequest = PrivacyResponse

// PrivacyResponse defines model for PrivacyResponse.
type PrivacyResponse struct {
	BirthDateVisibility string `json:"birth_date_visibility"`
	FriendRequestPolicy string `json:"friend_request_policy"`
	FriendsVisibility   string `json:"friends_visibility"`
	GenderVisibility    string `json:"gender_visibility"`
	LocationVisibility  string `json:"location_visibility"`
	MessagePolicy       string `json:"message_policy"`
	MusicVisibility     string `json:"music_visibility"`
	PhoneVisibility     string `json:"phone_visibility"`
	PostsVisibility     string `json:"posts_visibility"`
	ProfileVisibility   string `json:"profile_visibility"`
	StatusVisibility    string `json:"status_visibility"`
}

// ProfilePhotosResponse defines model for ProfilePhotosResponse.
type ProfilePhotosResponse struct {
	Albums       []PhotoAlbumPayload `json:"albums"`
	IsOwnProfile bool                `json:"is_own_profile"`
	OwnerID      string              `json:"owner_id"`
}

// ProfileResponse defines model for ProfileResponse.
type ProfileResponse struct {
	AvatarURL   string          `json:"avatar_url"`
	Bio         string          `json:"bio"`
	BirthDate   string          `json:"birth_date"`
	City        string          `json:"city"`
	Country     string          `json:"country"`
	CreatedAt   string          `json:"created_at"`
	FirstName   string          `json:"first_name"`
	Gender      string          `json:"gender"`
	Handle      *string         `json:"handle,omitempty"`
	LastName    string          `json:"last_name"`
	MiddleName  string          `json:"middle_name"`
	PhoneNumber string          `json:"phone_number"`
	Privacy     PrivacyResponse `json:"privacy"`
	Status      string          `json:"status"`
	Street      string          `json:"street"`
	UpdatedAt   string          `json:"updated_at"`
	UserID      string          `json:"user_id"`
}

// ProfilesResponse defines model for ProfilesResponse.
type ProfilesResponse struct {
	Profiles []ProfileResponse `json:"profiles"`
}

// SetHandleRequest defines model for SetHandleRequest.
type SetHandleRequest struct {
	Handle string `json:"handle"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status StatusResponseStatus `json:"status"`
}

// StatusResponseStatus defines model for StatusResponse.Status.
type StatusResponseStatus string

// UpdatePhotoRequest defines model for UpdatePhotoRequest.
type UpdatePhotoRequest struct {
	Archived  bool     `json:"archived"`
	Caption   string   `json:"caption"`
	Latitude  *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	Bio         string `json:"bio"`
	BirthDate   string `json:"birth_date"`
	City        string `json:"city"`
	Country     string `json:"country"`
	FirstName   string `json:"first_name"`
	Gender      string `json:"gender"`
	LastName    string `json:"last_name"`
	MiddleName  string `json:"middle_name"`
	PhoneNumber string `json:"phone_number"`
	Status      string `json:"status"`
	Street      string `json:"street"`
}
